version: "3.8"

services:
  db:
    platform: linux/arm64/v8
    image: mysql
    restart: unless-stopped
    env_file: .db-env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 3
  app:
    depends_on:
      - db
    restart: unless-stopped
    image: cafe-guide
    build: backend
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://db:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE",
      "spring.datasource.username" : "$MYSQL_USER",
      "spring.datasource.password" : "$MYSQL_ROOT_PASSWORD",
      "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
      "spring.jpa.show-sql": "true"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
